lidar_mapping_navigation_node:
  ros__parameters:
    mapping_min_object_size: 0.1   # Minimal ukuran objek yang diizinkan saat pemetaan (misalnya dalam meter)
    mapping_max_object_size: 2.0   # Maksimal ukuran objek yang diizinkan saat pemetaan (misalnya dalam meter)
    navigation_min_object_size: 0.2 # Minimal ukuran objek yang diizinkan saat navigasi (misalnya dalam meter)
    navigation_max_object_size: 1.5 # Maksimal ukuran objek yang diizinkan saat navigasi (misalnya dalam meter)
    filter_field_name: "z"         # Nama bidang filter (misalnya bidang z untuk kedalaman)
